###

Get http://localhost:5105/games/1

### 
Post http://localhost:5105/games
Content-Type: application/json

{
    "name": "Gdcfshost iojn of Tsusima -------",
    "genre": "Platform popo",
    "price": 60.00,
    "releaseDate": "2023-10-20"
}