### Genres ---------------------------
Get http://localhost:5105/genres

###
GET http://localhost:5105/genres/6

### 
POST http://localhost:5105/genres
Content-Type: application/json

{
    "name": "Fantasy"
}

###
DELETE http://localhost:5105/genres/6

###
PUT http://localhost:5105/genres/6
Content-Type: application/json

{
    "id": 6,
    "name": "Sci-Fi"
}

### Games --------------------------- 
GET http://localhost:5105/games

###
GET http://localhost:5105/games/3

###
Post http://localhost:5105/games
Content-Type: application/json

{
    "name": "star wars: jedi survivor",
    "genreId": 3,
    "price": 10.00,
    "releaseDate": "2023-10-20"

}

###
PUT http://localhost:5105/games/2
Content-Type: application/json

{
    "id": 2,
    "name": "Ghost of Tsushima",
    "genreId": 2,
    "price": 49.99,
    "releaseDate": "2020-07-17"
}
###

DELETE http://localhost:5105/games/2
###

